name: "OPUS 4 Documentation"

description: "OPUS 4 document repository software user manual"

author: "Jens Schwidder"

author_email: "schwidder@zib.de"

url: "https://opus4.github.io/userdoc"

baseurl: "/userdoc"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      weight: 0
      sort: "weight"
  -
    scope:
      path: "documenttypes"
    values:
      sort: "title"
  -
    scope:
      path: "config"
    values:
      sort: "title"
  -
    scope:
      path: "configext"
    values:
      sort: "title"
  -
    scope:
      path: "installation"
    values:
      sort: "title"

gems:
  - jekyll-sitemap
